In [33]:
LetterisNumber = {'a':1,'b':2,'c':3, 'd':4, 'e':5, 'f':6, 'g':7, 'h':8, 'i':9, 'j':10,
    'k':11, 'l':12, 'm':13, 'n':14, 'o':15, 'p':16, 'q':17, 'r':19, 's':19,
    't':20, 'u':21, 'v':22, 'w':23, 'x':24, 'y':25, 'z':26
}

def convert_letters_to_numbers(letters):
    return [LetterisNumber[char.lower()] for char in letters]

initials = "APC"
second_letters = "IBD"
row1 = convert_letters_to_numbers(initials)
row2 = convert_letters_to_numbers(second_letters)
matrix1 = np.array([row1, row2])

matrix2 = np.array([[2, 0, 2], [0, 4, 8]])

print("1st Matrix:")
print(matrix1)

print("\n2nd Matrix:")
print(matrix2)

matrix3 = matrix1 + matrix2
print("\n3rd Matrix (matrix1 + matrix2):")
print(matrix3)

matrix4 = matrix1 * 2
print("\n4th Matrix (matrix1 * 2):")
print(matrix4)

matrix5 = matrix2.T
print("\n5th Matrix (Transpose of Matrix2):")
print(matrix5)

matrix6 = np.dot(matrix3, matrix5)

print("\n6th Matrix (matrix3 x matrix5):")
print(matrix6)

sum_matrix3 = np.sum(matrix3)
print("\nSum of elements in 3rd Matrix:", sum_matrix3)

matrix7 = np.zeros((2,3), dtype=int)
print("\n7th Matrix (Zero Matrix 2x3):")
print(matrix7)

1st Matrix:
[[ 1 16  3]
 [ 9  2  4]]

2nd Matrix:
[[2 0 2]
 [0 4 8]]

3rd Matrix (matrix1 + matrix2):
[[ 3 16  5]
 [ 9  6 12]]

4th Matrix (matrix1 * 2):
[[ 2 32  6]
 [18  4  8]]

5th Matrix (Transpose of Matrix2):
[[2 0]
 [0 4]
 [2 8]]

6th Matrix (matrix3 x matrix5):
[[ 16 104]
 [ 42 120]]

Sum of elements in 3rd Matrix: 51

7th Matrix (Zero Matrix 2x3):
[[0 0 0]
 [0 0 0]]
